
const githubResult = """
{
  "total_count": 5953,
  "incomplete_results": false,
  "items": [
    {
      "login": "Filipe",
      "id": 27786693,
      "node_id": "MDQ6VXNlcjI3Nzg2Njkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/27786693?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Filipe",
      "html_url": "https://github.com/Filipe",
      "followers_url": "https://api.github.com/users/Filipe/followers",
      "following_url": "https://api.github.com/users/Filipe/following{/other_user}",
      "gists_url": "https://api.github.com/users/Filipe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Filipe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Filipe/subscriptions",
      "organizations_url": "https://api.github.com/users/Filipe/orgs",
      "repos_url": "https://api.github.com/users/Filipe/repos",
      "events_url": "https://api.github.com/users/Filipe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Filipe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipedeschamps",
      "id": 4248081,
      "node_id": "MDQ6VXNlcjQyNDgwODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4248081?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipedeschamps",
      "html_url": "https://github.com/filipedeschamps",
      "followers_url": "https://api.github.com/users/filipedeschamps/followers",
      "following_url": "https://api.github.com/users/filipedeschamps/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipedeschamps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipedeschamps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipedeschamps/subscriptions",
      "organizations_url": "https://api.github.com/users/filipedeschamps/orgs",
      "repos_url": "https://api.github.com/users/filipedeschamps/repos",
      "events_url": "https://api.github.com/users/filipedeschamps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipedeschamps/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ocefpaf",
      "id": 950575,
      "node_id": "MDQ6VXNlcjk1MDU3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/950575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ocefpaf",
      "html_url": "https://github.com/ocefpaf",
      "followers_url": "https://api.github.com/users/ocefpaf/followers",
      "following_url": "https://api.github.com/users/ocefpaf/following{/other_user}",
      "gists_url": "https://api.github.com/users/ocefpaf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ocefpaf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ocefpaf/subscriptions",
      "organizations_url": "https://api.github.com/users/ocefpaf/orgs",
      "repos_url": "https://api.github.com/users/ocefpaf/repos",
      "events_url": "https://api.github.com/users/ocefpaf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ocefpaf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipesilva",
      "id": 4172079,
      "node_id": "MDQ6VXNlcjQxNzIwNzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4172079?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipesilva",
      "html_url": "https://github.com/filipesilva",
      "followers_url": "https://api.github.com/users/filipesilva/followers",
      "following_url": "https://api.github.com/users/filipesilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipesilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipesilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipesilva/subscriptions",
      "organizations_url": "https://api.github.com/users/filipesilva/orgs",
      "repos_url": "https://api.github.com/users/filipesilva/repos",
      "events_url": "https://api.github.com/users/filipesilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipesilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeximenes",
      "id": 1180884,
      "node_id": "MDQ6VXNlcjExODA4ODQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1180884?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeximenes",
      "html_url": "https://github.com/filipeximenes",
      "followers_url": "https://api.github.com/users/filipeximenes/followers",
      "following_url": "https://api.github.com/users/filipeximenes/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeximenes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeximenes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeximenes/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeximenes/orgs",
      "repos_url": "https://api.github.com/users/filipeximenes/repos",
      "events_url": "https://api.github.com/users/filipeximenes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeximenes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipelinhares",
      "id": 2338778,
      "node_id": "MDQ6VXNlcjIzMzg3Nzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2338778?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipelinhares",
      "html_url": "https://github.com/filipelinhares",
      "followers_url": "https://api.github.com/users/filipelinhares/followers",
      "following_url": "https://api.github.com/users/filipelinhares/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipelinhares/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipelinhares/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipelinhares/subscriptions",
      "organizations_url": "https://api.github.com/users/filipelinhares/orgs",
      "repos_url": "https://api.github.com/users/filipelinhares/repos",
      "events_url": "https://api.github.com/users/filipelinhares/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipelinhares/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipenevola",
      "id": 437372,
      "node_id": "MDQ6VXNlcjQzNzM3Mg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/437372?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipenevola",
      "html_url": "https://github.com/filipenevola",
      "followers_url": "https://api.github.com/users/filipenevola/followers",
      "following_url": "https://api.github.com/users/filipenevola/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipenevola/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipenevola/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipenevola/subscriptions",
      "organizations_url": "https://api.github.com/users/filipenevola/orgs",
      "repos_url": "https://api.github.com/users/filipenevola/repos",
      "events_url": "https://api.github.com/users/filipenevola/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipenevola/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipealvesdef",
      "id": 10976512,
      "node_id": "MDQ6VXNlcjEwOTc2NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/10976512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipealvesdef",
      "html_url": "https://github.com/filipealvesdef",
      "followers_url": "https://api.github.com/users/filipealvesdef/followers",
      "following_url": "https://api.github.com/users/filipealvesdef/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipealvesdef/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipealvesdef/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipealvesdef/subscriptions",
      "organizations_url": "https://api.github.com/users/filipealvesdef/orgs",
      "repos_url": "https://api.github.com/users/filipealvesdef/repos",
      "events_url": "https://api.github.com/users/filipealvesdef/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipealvesdef/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecosta90",
      "id": 5832149,
      "node_id": "MDQ6VXNlcjU4MzIxNDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5832149?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecosta90",
      "html_url": "https://github.com/filipecosta90",
      "followers_url": "https://api.github.com/users/filipecosta90/followers",
      "following_url": "https://api.github.com/users/filipecosta90/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecosta90/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecosta90/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecosta90/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecosta90/orgs",
      "repos_url": "https://api.github.com/users/filipecosta90/repos",
      "events_url": "https://api.github.com/users/filipecosta90/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecosta90/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipekiss",
      "id": 48519,
      "node_id": "MDQ6VXNlcjQ4NTE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/48519?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipekiss",
      "html_url": "https://github.com/filipekiss",
      "followers_url": "https://api.github.com/users/filipekiss/followers",
      "following_url": "https://api.github.com/users/filipekiss/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipekiss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipekiss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipekiss/subscriptions",
      "organizations_url": "https://api.github.com/users/filipekiss/orgs",
      "repos_url": "https://api.github.com/users/filipekiss/repos",
      "events_url": "https://api.github.com/users/filipekiss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipekiss/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebarcos",
      "id": 303141,
      "node_id": "MDQ6VXNlcjMwMzE0MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/303141?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebarcos",
      "html_url": "https://github.com/filipebarcos",
      "followers_url": "https://api.github.com/users/filipebarcos/followers",
      "following_url": "https://api.github.com/users/filipebarcos/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebarcos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebarcos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebarcos/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebarcos/orgs",
      "repos_url": "https://api.github.com/users/filipebarcos/repos",
      "events_url": "https://api.github.com/users/filipebarcos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebarcos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeflop",
      "id": 4410043,
      "node_id": "MDQ6VXNlcjQ0MTAwNDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4410043?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeflop",
      "html_url": "https://github.com/filipeflop",
      "followers_url": "https://api.github.com/users/filipeflop/followers",
      "following_url": "https://api.github.com/users/filipeflop/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeflop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeflop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeflop/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeflop/orgs",
      "repos_url": "https://api.github.com/users/filipeflop/repos",
      "events_url": "https://api.github.com/users/filipeflop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeflop/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeamoreira",
      "id": 8424,
      "node_id": "MDQ6VXNlcjg0MjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8424?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeamoreira",
      "html_url": "https://github.com/filipeamoreira",
      "followers_url": "https://api.github.com/users/filipeamoreira/followers",
      "following_url": "https://api.github.com/users/filipeamoreira/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeamoreira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeamoreira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeamoreira/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeamoreira/orgs",
      "repos_url": "https://api.github.com/users/filipeamoreira/repos",
      "events_url": "https://api.github.com/users/filipeamoreira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeamoreira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecifali",
      "id": 975041,
      "node_id": "MDQ6VXNlcjk3NTA0MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/975041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecifali",
      "html_url": "https://github.com/filipecifali",
      "followers_url": "https://api.github.com/users/filipecifali/followers",
      "following_url": "https://api.github.com/users/filipecifali/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecifali/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecifali/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecifali/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecifali/orgs",
      "repos_url": "https://api.github.com/users/filipecifali/repos",
      "events_url": "https://api.github.com/users/filipecifali/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecifali/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebraida",
      "id": 2746730,
      "node_id": "MDQ6VXNlcjI3NDY3MzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2746730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebraida",
      "html_url": "https://github.com/filipebraida",
      "followers_url": "https://api.github.com/users/filipebraida/followers",
      "following_url": "https://api.github.com/users/filipebraida/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebraida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebraida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebraida/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebraida/orgs",
      "repos_url": "https://api.github.com/users/filipebraida/repos",
      "events_url": "https://api.github.com/users/filipebraida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebraida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipealva",
      "id": 6117280,
      "node_id": "MDQ6VXNlcjYxMTcyODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6117280?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipealva",
      "html_url": "https://github.com/filipealva",
      "followers_url": "https://api.github.com/users/filipealva/followers",
      "following_url": "https://api.github.com/users/filipealva/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipealva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipealva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipealva/subscriptions",
      "organizations_url": "https://api.github.com/users/filipealva/orgs",
      "repos_url": "https://api.github.com/users/filipealva/repos",
      "events_url": "https://api.github.com/users/filipealva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipealva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipemacedo",
      "id": 28747696,
      "node_id": "MDQ6VXNlcjI4NzQ3Njk2",
      "avatar_url": "https://avatars.githubusercontent.com/u/28747696?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipemacedo",
      "html_url": "https://github.com/filipemacedo",
      "followers_url": "https://api.github.com/users/filipemacedo/followers",
      "following_url": "https://api.github.com/users/filipemacedo/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipemacedo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipemacedo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipemacedo/subscriptions",
      "organizations_url": "https://api.github.com/users/filipemacedo/orgs",
      "repos_url": "https://api.github.com/users/filipemacedo/repos",
      "events_url": "https://api.github.com/users/filipemacedo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipemacedo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeleonelbatista",
      "id": 20867392,
      "node_id": "MDQ6VXNlcjIwODY3Mzky",
      "avatar_url": "https://avatars.githubusercontent.com/u/20867392?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeleonelbatista",
      "html_url": "https://github.com/filipeleonelbatista",
      "followers_url": "https://api.github.com/users/filipeleonelbatista/followers",
      "following_url": "https://api.github.com/users/filipeleonelbatista/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeleonelbatista/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeleonelbatista/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeleonelbatista/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeleonelbatista/orgs",
      "repos_url": "https://api.github.com/users/filipeleonelbatista/repos",
      "events_url": "https://api.github.com/users/filipeleonelbatista/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeleonelbatista/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipesperandio",
      "id": 316873,
      "node_id": "MDQ6VXNlcjMxNjg3Mw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/316873?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipesperandio",
      "html_url": "https://github.com/filipesperandio",
      "followers_url": "https://api.github.com/users/filipesperandio/followers",
      "following_url": "https://api.github.com/users/filipesperandio/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipesperandio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipesperandio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipesperandio/subscriptions",
      "organizations_url": "https://api.github.com/users/filipesperandio/orgs",
      "repos_url": "https://api.github.com/users/filipesperandio/repos",
      "events_url": "https://api.github.com/users/filipesperandio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipesperandio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipevarjao",
      "id": 777456,
      "node_id": "MDQ6VXNlcjc3NzQ1Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/777456?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipevarjao",
      "html_url": "https://github.com/filipevarjao",
      "followers_url": "https://api.github.com/users/filipevarjao/followers",
      "following_url": "https://api.github.com/users/filipevarjao/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipevarjao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipevarjao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipevarjao/subscriptions",
      "organizations_url": "https://api.github.com/users/filipevarjao/orgs",
      "repos_url": "https://api.github.com/users/filipevarjao/repos",
      "events_url": "https://api.github.com/users/filipevarjao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipevarjao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipesaraiva",
      "id": 203142,
      "node_id": "MDQ6VXNlcjIwMzE0Mg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/203142?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipesaraiva",
      "html_url": "https://github.com/filipesaraiva",
      "followers_url": "https://api.github.com/users/filipesaraiva/followers",
      "following_url": "https://api.github.com/users/filipesaraiva/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipesaraiva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipesaraiva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipesaraiva/subscriptions",
      "organizations_url": "https://api.github.com/users/filipesaraiva/orgs",
      "repos_url": "https://api.github.com/users/filipesaraiva/repos",
      "events_url": "https://api.github.com/users/filipesaraiva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipesaraiva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Filipe-p",
      "id": 24757391,
      "node_id": "MDQ6VXNlcjI0NzU3Mzkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/24757391?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Filipe-p",
      "html_url": "https://github.com/Filipe-p",
      "followers_url": "https://api.github.com/users/Filipe-p/followers",
      "following_url": "https://api.github.com/users/Filipe-p/following{/other_user}",
      "gists_url": "https://api.github.com/users/Filipe-p/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Filipe-p/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Filipe-p/subscriptions",
      "organizations_url": "https://api.github.com/users/Filipe-p/orgs",
      "repos_url": "https://api.github.com/users/Filipe-p/repos",
      "events_url": "https://api.github.com/users/Filipe-p/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Filipe-p/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeportes",
      "id": 1385552,
      "node_id": "MDQ6VXNlcjEzODU1NTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1385552?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeportes",
      "html_url": "https://github.com/filipeportes",
      "followers_url": "https://api.github.com/users/filipeportes/followers",
      "following_url": "https://api.github.com/users/filipeportes/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeportes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeportes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeportes/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeportes/orgs",
      "repos_url": "https://api.github.com/users/filipeportes/repos",
      "events_url": "https://api.github.com/users/filipeportes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeportes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filp",
      "id": 382538,
      "node_id": "MDQ6VXNlcjM4MjUzOA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/382538?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filp",
      "html_url": "https://github.com/filp",
      "followers_url": "https://api.github.com/users/filp/followers",
      "following_url": "https://api.github.com/users/filp/following{/other_user}",
      "gists_url": "https://api.github.com/users/filp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filp/subscriptions",
      "organizations_url": "https://api.github.com/users/filp/orgs",
      "repos_url": "https://api.github.com/users/filp/repos",
      "events_url": "https://api.github.com/users/filp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "FFY00",
      "id": 11718923,
      "node_id": "MDQ6VXNlcjExNzE4OTIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/11718923?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/FFY00",
      "html_url": "https://github.com/FFY00",
      "followers_url": "https://api.github.com/users/FFY00/followers",
      "following_url": "https://api.github.com/users/FFY00/following{/other_user}",
      "gists_url": "https://api.github.com/users/FFY00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/FFY00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/FFY00/subscriptions",
      "organizations_url": "https://api.github.com/users/FFY00/orgs",
      "repos_url": "https://api.github.com/users/FFY00/repos",
      "events_url": "https://api.github.com/users/FFY00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/FFY00/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebezerra",
      "id": 1006095,
      "node_id": "MDQ6VXNlcjEwMDYwOTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1006095?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebezerra",
      "html_url": "https://github.com/filipebezerra",
      "followers_url": "https://api.github.com/users/filipebezerra/followers",
      "following_url": "https://api.github.com/users/filipebezerra/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebezerra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebezerra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebezerra/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebezerra/orgs",
      "repos_url": "https://api.github.com/users/filipebezerra/repos",
      "events_url": "https://api.github.com/users/filipebezerra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebezerra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "falkTX",
      "id": 1334853,
      "node_id": "MDQ6VXNlcjEzMzQ4NTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1334853?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/falkTX",
      "html_url": "https://github.com/falkTX",
      "followers_url": "https://api.github.com/users/falkTX/followers",
      "following_url": "https://api.github.com/users/falkTX/following{/other_user}",
      "gists_url": "https://api.github.com/users/falkTX/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/falkTX/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/falkTX/subscriptions",
      "organizations_url": "https://api.github.com/users/falkTX/orgs",
      "repos_url": "https://api.github.com/users/falkTX/repos",
      "events_url": "https://api.github.com/users/falkTX/events{/privacy}",
      "received_events_url": "https://api.github.com/users/falkTX/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipemerker",
      "id": 9748039,
      "node_id": "MDQ6VXNlcjk3NDgwMzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9748039?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipemerker",
      "html_url": "https://github.com/filipemerker",
      "followers_url": "https://api.github.com/users/filipemerker/followers",
      "following_url": "https://api.github.com/users/filipemerker/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipemerker/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipemerker/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipemerker/subscriptions",
      "organizations_url": "https://api.github.com/users/filipemerker/orgs",
      "repos_url": "https://api.github.com/users/filipemerker/repos",
      "events_url": "https://api.github.com/users/filipemerker/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipemerker/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipenatanael",
      "id": 14134758,
      "node_id": "MDQ6VXNlcjE0MTM0NzU4",
      "avatar_url": "https://avatars.githubusercontent.com/u/14134758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipenatanael",
      "html_url": "https://github.com/filipenatanael",
      "followers_url": "https://api.github.com/users/filipenatanael/followers",
      "following_url": "https://api.github.com/users/filipenatanael/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipenatanael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipenatanael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipenatanael/subscriptions",
      "organizations_url": "https://api.github.com/users/filipenatanael/orgs",
      "repos_url": "https://api.github.com/users/filipenatanael/repos",
      "events_url": "https://api.github.com/users/filipenatanael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipenatanael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ninrod",
      "id": 8352747,
      "node_id": "MDQ6VXNlcjgzNTI3NDc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8352747?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ninrod",
      "html_url": "https://github.com/ninrod",
      "followers_url": "https://api.github.com/users/ninrod/followers",
      "following_url": "https://api.github.com/users/ninrod/following{/other_user}",
      "gists_url": "https://api.github.com/users/ninrod/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ninrod/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ninrod/subscriptions",
      "organizations_url": "https://api.github.com/users/ninrod/orgs",
      "repos_url": "https://api.github.com/users/ninrod/repos",
      "events_url": "https://api.github.com/users/ninrod/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ninrod/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
